# Generated by Django 3.2.6 on 2021-08-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_venda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': [('setar_nfe', 'Usuário pode alterar parametro NFE'), ('ver_dashboard', 'Usuário pode visualizar dashboard')]},
        ),
    ]
