# Generated by Django 3.2.6 on 2021-08-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20210812_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='ItemDoPedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
